{lib, ...}: let
  inherit (lib) splitString concatMapStringsSep;
  inherit (lib.strings) replicate;
  prefix = prefix: text:
    lib.pipe text [
      (splitString "\n")
      (concatMapStringsSep "\n" (s: "${prefix}${s}"))
    ];
  i = indent: prefix (replicate indent "  ");
in {
  script = rec {
    header = "Generated by Consona";
    mkScript = {
      bash = desc: body: ''
        ${prefix "# " "${header}\n${desc}"}
        ${body}
      '';
    };
    mkCodeIfElseHighColor = {
      bash = high: low:
      # bash
      ''
        if [[ $(tput colors) -gt 8 ]]; then
        ${i 1 high}
        else
        ${i 1 low}
        fi
      '';
    };
  };
}
